import { AlertOutlined, BookOutlined, CalendarOutlined, ContactsOutlined, PieChartOutlined, SettingFilled, ShopOutlined, UserDeleteOutlined } from "@ant-design/icons";

export const sidebarMenus = [
  {
    name: 'Overview',
    id: 'Ringkasan',
    path: '/overview',
    icon: <PieChartOutlined />,
    role: ['admin', 'guest'],
    subroute: [],
  },
  {
    name: 'Tickets',
    id: 'Tiket',
    path: '/tickets',
    icon: <CalendarOutlined />,
    role: ['admin', 'guest'],
    subroute: [],
  },
  {
    name: 'Ideas',
    id: 'Ide',
    path: '/ideas',
    icon: <AlertOutlined />,
    role: ['admin'],
    subroute: [],
  },
  {
    name: 'Contacts',
    id: 'Kontak',
    path: '/contacts',
    icon: <ContactsOutlined />,
    role: ['admin'],
    subroute: [],
  },
  {
    name: 'Agents',
    id: 'Agen',
    path: '/agents',
    icon: <UserDeleteOutlined />,
    role: ['admin'],
    subroute: [],
  },
  {
    name: 'Articles',
    id: 'Artikel',
    path: '/articles',
    icon: <BookOutlined />,
    role: ['admin'],
    subroute: [],
  },
  {
    name: '',
    id: '',
    path: '',
    icon: null,
    role: ['admin'],
    subroute: [],
  },
  {
    name: 'Settings',
    id: 'Pengaturan',
    path: '/settings',
    icon: <SettingFilled />,
    role: ['admin'],
    subroute: [],
  },
  {
    name: 'Subscription',
    id: 'Langganan',
    path: '/subscription',
    icon: <ShopOutlined />,
    role: ['admin'],
    subroute: [],
  },
];
